#!/usr/bin/env bash

# Copyright (C) 2018-19 Akhil Narang
# SPDX-License-Identifier: GPL-3.0-only

# Script with some aliases and exports

if [[ "$(command -v hub)" ]]; then
    alias git='hub'
fi

# Miscellaneous aliases
alias setperf='echo "performance" | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor'
alias setsave='echo "powersave" | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor'
alias path='echo ${PATH}'

# Set default editor to nano
export EDITOR="nano"

# Set timezone
export TZ="Asia/Kolkata"

alias camera_off="echo '\_SB.ATKD.WMNB 0x00 0x53564544 0x0000000000060078' | sudo tee /proc/acpi/call"
alias camera_on="echo '\_SB.ATKD.WMNB 0x00 0x53564544 0x0000000100060078' | sudo tee /proc/acpi/call"
