#!/usr/bin/env bash

# Copyright (C) 2018 Akhil Narang
# Copyright (C) 2018 Harsh Shandilya <msfjarvis@gmail.com>
# SPDX-License-Identifier: GPL-3.0-only
# Kernel release script

source ~/scripts/functions

SERVER_IP="178.63.101.252"
DOWNLOAD_HOST="https://downloads.akhilnarang.me"
MIRROR_HOST="https://mirror.akhilnarang.me"
KERNEL_PATH="kernel/whyred"
NAME=$(ssh "${SERVER_IP}" ls /var/www/downloads.akhilnarang.me/"${KERNEL_PATH}"/Test/*.zip | tail -1)
DERPVERSION="${1:?}"
TAG="Derp-v${DERPVERSION}"
RELEASE_ZIPNAME="${TAG}.zip"
CHANGELOG="${2}"

sendDerp "Releasing Derp v$DERPVERSION"
sendDerp "Derp v$DERPVERSION is up, grab it [here](${DOWNLOAD_HOST}/${KERNEL_PATH}/Stable/${RELEASE_ZIPNAME}) or [here](${MIRROR_HOST}/${KERNEL_PATH}/Stable/${RELEASE_ZIPNAME})"
ssh "${SERVER_IP}" "cp -v ${NAME} /var/www/downloads.akhilnarang.me/${KERNEL_PATH}/Stable/${RELEASE_ZIPNAME}; cd /var/www/downloads.akhilnarang.me/${KERNEL_PATH}/Stable; md5sum ${RELEASE_ZIPNAME} > ${RELEASE_ZIPNAME}.md5sum";
ssh "${SERVER_IP}" ./bin/mirrorsync
sendDerp "Changelog:
\`\`\`
${CHANGELOG}
\`\`\`"

cd "${KERNELDIR}"/whyred
git tag -as "${TAG}"
git p origin "${TAG}"
cd /tmp
wget "${MIRROR_HOST}/${KERNEL_PATH}/Stable/${RELEASE_ZIPNAME}"
wget "${MIRROR_HOST}/${KERNEL_PATH}/Stable/${RELEASE_ZIPNAME}.md5sum"
cd -
hub release create "${TAG}" -a "/tmp/${RELEASE_ZIPNAME}" -a "/tmp/${RELEASE_ZIPNAME}.md5sum"
rm "/tmp/${RELEASE_ZIPNAME}" "/tmp/${RELEASE_ZIPNAME}.md5sum"
sendTG kronic me md "${TAG} released!"
git push git@github.com:AOSIP-Devices/kernel_xiaomi_sdm660 --force
