#!/usr/bin/env bash

# Copyright (C) 2018 Akhil Narang
# Copyright (C) 2018 Harsh Shandilya <msfjarvis@gmail.com>
# SPDX-License-Identifier: GPL-3.0-only
# Kernel release script

source ~/scripts/functions

DOWNLOAD_HOST="downloads.akhilnarang.me"
MIRROR_HOST="mirror.akhilnarang.me"
KERNEL_PATH="kernel/whyred"
NAME=$(ssh "${DOWNLOAD_HOST}" ls /var/www/downloads.akhilnarang.me/"${KERNEL_PATH}"/Test/*.zip | tail -1)
DERPVERSION="${1:?}"
TAG="Derp-v${DERPVERSION}"
RELEASE_ZIPNAME="${TAG}.zip"
CHANGELOG="${2}"

sendTG kronic derp md "Releasing Derp v$DERPVERSION"

ssh "${DOWNLOAD_HOST}" "cp -v ${NAME} /var/www/downloads.akhilnarang.me/${KERNEL_PATH}/Stable/${RELEASE_ZIPNAME}; cd /var/www/downloads.akhilnarang.me/${KERNEL_PATH}/Stable; md5sum ${RELEASE_ZIPNAME} > ${RELEASE_ZIPNAME}.md5sum";
ssh "${DOWNLOAD_HOST}" ./bin/mirrorsync
sendTG kronic derp md "Derp v$DERPVERSION is up, grab it [here](https://${DOWNLOAD_HOST}/${KERNEL_PATH}/Stable/${RELEASE_ZIPNAME}) or [here](https://${MIRROR_HOST}/${KERNEL_PATH}/Stable/${RELEASE_ZIPNAME})"
sendTG kronic derp md "Changelog:"
sendTG kronic derp md "\`\`\`${CHANGELOG}\`\`\`"

cd "${KERNELDIR}"/whyred
git tag -as "${TAG}"
git p origin "${TAG}"
cd /tmp
wget "https://${MIRROR_HOST}/${KERNEL_PATH}/Stable/${RELEASE_ZIPNAME}"
wget "https://${MIRROR_HOST}/${KERNEL_PATH}/Stable/${RELEASE_ZIPNAME}.md5sum"
cd -
hub release create "${TAG}" -a "/tmp/${RELEASE_ZIPNAME}" -a "/tmp/${RELEASE_ZIPNAME}.md5sum"
rm "/tmp/${RELEASE_ZIPNAME}*" -v
sendTG kronic me md "${TAG} released!"
